theme: jekyll-theme-architect
title: Foote-Step Findings
description: Repository for experimental procedures, set ups & findings based on repetition of Eunice Newton Foote's early uncovering what we now know as the 'Greenhouse Gas Effect'
